config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  } #ゲストログイン消去&編集防止collection do
  devise_scope :user do #ゲストログイン機能
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root to: "products#index"

  resources :users, only: [:index, :show] do #マイページ
    collection do
      get :likes
    end
  end
  resources :products do
    resources :comments, only: [:create, :destroy, :show, :index] #productコントローラのindexとshowにコメントのidを渡す為、:show, :indexを追加した
    collection do  # ↓カテゴリー機能
      get 'products/new/mid_category', to: 'products#mid_category'
      get 'search' #検索機能
    end
  end
  post   '/like/:product_id' => 'likes#like',   as: 'like'
  delete '/like/:product_id' => 'likes#unlike', as: 'unlike'

  get  '/inquiry', to: 'static_pages#inquiry'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :product #, counter_cache: :likes_count
  belongs_to :user

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables

  def like
    #Userモデルの呼び出しをcurrent_userで行う。これにより、自動的にuser_idにcurrent_user.idが指定される。
    like = current_user.likes.new(product_id: @product.id)
    # binding.pry
    like.save
  end

  def unlike
    like = current_user.likes.find_by(product_id: @product.id)
    like.destroy
  end

  private

  def set_variables
    @product = Product.find(params[:product_id])
    @id_name = "#like-link-#{@product.id}"
    # @id_nameは非同期の時に使う
  end

end

app/views/likes/_like.html.haml
.like-link{:id => "like-link-#{product.id}"}
  - if user_signed_in?
    - if current_user.likes.find_by(product_id: product.id)
      .like-border
        = link_to unlike_path(product.id), class: "like-button", method: :delete, remote: true do
          .iine-button
            %i.fas.fa-heart.heart.animated.rubberBand
            Good！
            = product.likes.count
    - else
      .unlike-border
        = link_to like_path(product.id), class: "unlike-button", method: :post, remote: true do
          .iine-button
            %i.far.fa-heart.heart
            Good！
            = product.likes.count
  - else
    .like-border
      = link_to new_user_session_path, class: "like-button" do
        .iine-button
          %i.fas.fa-heart.heart.animated.rubberBand
          Good！
          = product.likes.count

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", product: @product  )) %>');

<%# jsファイル内でrenderメソッドを用いる場合はescape_javascriptメソッドでrender部分を囲む。 %>

app/views/likes/unlike.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", product: @product  )) %>');

<%# jsファイル内でrenderメソッドを用いる場合はescape_javascriptメソッドでrender部分を囲む。 %>