config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  } #ゲストログイン消去&編集防止collection do
  devise_scope :user do #ゲストログイン機能
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root to: "products#index"

  resources :users, only: [:index, :show] do #マイページ
    collection do
      get :likes
    end
  end
  resources :products do
    resources :comments, only: [:create, :destroy, :show, :index] #productコントローラのindexとshowにコメントのidを渡す為、:show, :indexを追加した
    collection do  # ↓カテゴリー機能
      get 'products/new/mid_category', to: 'products#mid_category'
      get 'search' #検索機能
    end
  end
  post   '/like/:product_id' => 'likes#like',   as: 'like'
  delete '/like/:product_id' => 'likes#unlike', as: 'unlike'

  get  '/inquiry', to: 'static_pages#inquiry'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

  has_many :products, dependent: :destroy
  has_many :comments, dependent: :destroy  # commentsテーブルとのアソシエーション
  has_many :likes, dependent: :destroy
  has_many :like_products, through: :likes, source: :product
  has_many :sns_credentials, dependent: :destroy

  mount_uploader :image, ImageUploader # アイコン投稿のアソシエーション

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 10}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true, uniqueness: true, length: { maximum: 100 }, format: { with: VALID_EMAIL_REGEX }
  # validates :password_confirmation, presence: true, length: { in: 6..30 }
  # uniqueness 同一データは一つのみ許可する

  #ゲストログイン
  def self.guest
    find_or_create_by!(name: 'guest', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end

  # < sns 認証 >
  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      name: auth.info.name,
      email: auth.info.email
    )
    if user.persisted?  #userが登録済みの場合はそのままログインの処理へ行くので、ここでsnsのuser_idを更新しておく
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }  #User.form_omniauth、メゾットでuserとsnsをハッシュで返す
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    authorization
  end

  def failure
    redirect_to root_path
  end

  private

  def authorization
    sns_info = User.from_omniauth(request.env["omniauth.auth"])
    @user = sns_info[:user]
      #APIから受け取ったレスポンスがrequest.env["omniauth.auth"]という変数に入っている
      #DB操作を行うメソッドUser.from_omniauthを仮で作り、上記変数を渡す
      #Userモデルのインスタンスを返させて＠userへ代入することで、その後の処理でdeviseのヘルパーを利用することができる


    if @user.persisted? #ユーザー情報が登録済みなので、新規登録ではなくログイン処理を行う
      sign_in_and_redirect @user, event: :authentication
    else #ユーザー情報が未登録なので、新規登録画面へ遷移する
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  before_action :check_guest, only: :create
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: %i[update destroy]
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    user = User.find(params[:id])
    @name = current_user.name
    #ページネーション&最新投稿を一番上に表示
    @products = user.products.page(params[:page]).per(5).order("created_at DESC")
    #カテゴリーの呼び出し
    @parents = Category.order("id ASC").limit(16)
  end
end

app/views/users/likes.html.haml
= render partial: "products/header", locals: { product: @products }
%main.main
  .like-content
    %h2.like_form Goodした動画の一覧
    - current_user.like_products.last(10).each do |product|
      =link_to product_path(product), class: "mypage-product-link" do
        .mypage-product_video
          = video_tag(product.image_url.to_s, height: "120", width: "160 ") if product.image?
        .mypage-product-body
          .mypage-product-name
            動画投稿者:
            = product.title
          .mypage-product-time
            投稿日時:
            = product.created_at.strftime('%Y/%m/%d %H:%M:%S')
          .mypage-product-good
            合計Good数:
            = product.likes.count
        -# %i.fas.fa-chevron-right
.blank
= render "products/footer"

app/views/users/show.html.haml
= render "products/header"
%main.main
  - @products.each do |product|
    .blank
    .show_user
      .content_main
        .content_left
          .content_video
            = video_tag(product.image_url.to_s, autoplay: false, muted: true, controls: true, preload: true, class: "user_show_video", id: "user_show_video_preview") if product.image?
        .content_right
          .content_icon
            .content_icon_left
              .content_icon_left_image
                - if product.user.image?
                  = image_tag(product.user.image.to_s, class: "user_icon_image",alt:"no-image")
                - else
                  = image_tag asset_path("default.png"), alt: "no-image"
            .content__right
              .content__right__top
                = product.title
              .content__right__bottom
                .content__right__bottom--date
                  = product.created_at.strftime('%Y/%m/%d %H:%M:%S')
          .content_user_show
            .content_posts
              %table
                %tbody
                  %tr
                    %th ペン回し歴
                    %td
                      = product.pen_history.value
            .content_posts
              %table
                %tbody
                  %tr
                    %th ペンの種類
                    %td.category
                      - @parents.each do |parent|
                        - if product.category_id == parent.id
                          -# = link_to "#" do
                          -#   = parent.parent.name
                          = link_to "#" ,class: "category_font" do
                            = parent.name
            .content_posts
              %table
                %tbody
                  %tr
                    %th good数
                    %td
                      = product.likes.count
          .content_user_show
            .user_show_retrun
              = link_to '投稿編集', "/products/#{product.id}/edit", method: :get, class: "show_user_return_bottun"
              = link_to '投稿削除', "/products/#{product.id}", class: "show_user_return_bottun", method: :delete, data:{ confirm: '動画を削除しますか？',cancel: 'やめる',commit: '削除'}, title: '削除の確認'
            .user_show_retrun
              = link_to '詳細ページ', "/products/#{product.id}", method: :get, class: "show_user_return_bottun"
              = link_to 'トップページ', "/", method: :get, class: "show_user_return_bottun"

      .content_show_down
        %table
          %tbody
            %tr
              %th.user_show_contes_th
                動画の説明
              %td.user_show_contes_tb
                = simple_format(product.text)

  = paginate(@products)
.blank
= render "products/footer"