config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  } #ゲストログイン消去&編集防止collection do
  devise_scope :user do #ゲストログイン機能
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root to: "products#index"

  resources :users, only: [:index, :show] do #マイページ
    collection do
      get :likes
    end
  end
  resources :products do
    resources :comments, only: [:create, :destroy, :show, :index] #productコントローラのindexとshowにコメントのidを渡す為、:show, :indexを追加した
    collection do  # ↓カテゴリー機能
      get 'products/new/mid_category', to: 'products#mid_category'
      get 'search' #検索機能
    end
  end
  post   '/like/:product_id' => 'likes#like',   as: 'like'
  delete '/like/:product_id' => 'likes#unlike', as: 'unlike'

  get  '/inquiry', to: 'static_pages#inquiry'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'

end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  # gem 'active_hash'を導入したら、extend ActiveHash::Associations::ActiveRecordExtensionsとbelongs_to_active_hash :〇〇(モデル名)を記述する
  belongs_to_active_hash :pen_history, presence: true
  belongs_to :user
  has_many :category # カテゴリー機能
  has_many :comments, dependent: :destroy # commentsテーブルとのアソシエーション
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  mount_uploader :image, ImageUploader, dependent: :destroy # 動画投稿のアソシエーション

  validates :image,:pen_history_id, :category_id, presence: true
  validates :text,presence: true, length: {maximum: 1000} #商品説明が1000文字しか打てない様に設定した
  validates :title, presence: true, length: {maximum: 10}

  def self.search(search)
    if search
      Product.where('title LIKE(?)', "%#{search}%")
    else
      Product.all
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :show, :update, :destroy]

  def index
    @products = Product.includes(:user).order("created_at DESC").page(params[:page]).per(5)
    @parents = Category.order("id ASC").limit(16)
  end

  def show
    @parents = Category.order("id ASC").limit(16)
    @comment = Comment.new
    @comments = @product.comments.includes(:user)
  end

  #検索機能
  def search
    @products = Product.search(params[:keyword]).order("created_at DESC").page(params[:page]).per(5)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      render :create
    else
      render :new
    end
  end


  def destroy
    if @product.destroy
      render :destory
    else
      redirect_to product_path(@product.id)
    end
  end

  def edit
    @parents = Category.order("id ASC").limit(16)
    # 下記コードは、編集時に動画データがなくなるため、キャッシュで保存させてる(公式ドキュメントに記述例あり)
    @product.image.cache! unless @product.image.blank?
  end

  def update
    @parents = Category.order("id ASC").limit(16)
    if @product.update(product_params)
      render :update
    else
      flash[:alert] = '正しく入力してください'
    redirect_to edit_product_path(@product.id)
    end
  end

  #カテゴリー機能
  def mid_category
    @mid_categories = Category.where(ancestry: params[:big_category_id])
    render json: @mid_categories
  end




    private
    def product_params
      params.require(:product).permit(:title, :pen_history_id, :category_id, :youtube_url, :text ,:image,:image_cache).merge(user_id: current_user.id)
    end

    def set_product
      @product = Product.find(params[:id])
      # :edit, :update, :showにitem.idを与える必要がある為、記述した
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_error_message.html.haml
-if @product.errors.any?
  .alert_new_edit
    %ul
      -@product.errors.full_messages.each do |message|
        %li= message

app/views/products/_footer.html.haml
.footer
  = link_to "利用規約", about_path, class: 'content_input'
  = link_to "プライバシーポリシー", inquiry_path ,class: 'content_input'
  = link_to "問い合わせ", root_path ,class: 'content_input'

app/views/products/_form.html.haml
.form-group
  .post_video
    動画投稿
    %span.form-require 必須
  .post_video_preview
    = video_tag(@product.image_url.to_s, autoplay: true, muted: true, controls: true, preload: false, loop: true, class: "video-preview", id: "preview")
    = form.label :image ,"動画をアップロード", class: "image_input_btn"
    = form.file_field :image, accept: 'video/*', class: "image_form" ,onchange: 'previewImage(preview)'
    = form.hidden_field :image_cache
  %small.note
    ※ 動画はmp4の拡張子のみ投稿できます。こちらのサイトからmp4に変換できます。
    = link_to "mp4に変換",  "https://www.aconvert.com/jp/video/mov-to-mp4/",class: "video_site"
    %br/
    ※ 投稿できる動画のデータ最大要領は10MBまでです。
.form-group
  = form.label :title , class: "product_title" do
    ニックネーム
    %span.form-require 必須
  = form.text_field :title, placeholder: "ニックネーム(10文字以内)", class: "input-form"
.form-group
  = form.label :text do
    動画の説明
    %span.form-require 必須
  = form.text_area :text, placeholder: "動画の説明を500文字以内でご記入ください", rows: "5", class: "form_textarea"

-# ユーチューブの投稿
-# = form.label :youtube_url do
-#     動画投稿
-#     %span.form-require 必須
-#   = form.text_field :youtube_url, placeholder: "youtubeのURLを記載して下さい", class: "input-default"

-# 簡易videoプレヴュー表示
-# = video_tag(@product.image_url.to_s, autoplay: false, muted: true, controls: true, preload: true, width: 550) if @product.image && @product.image.url.to_s

app/views/products/_header.html.haml
%header.header1
  %nav.navbar.navbar-expand.navbar-light.up
    = link_to "Penspinning Videos", root_path, class: 'navbar-brand text-white font-weight-bold'
.header2
  %nav.navbar.navbar-expand.navbar-light.down
    %ul.navbar-nav.left__title
      - if user_signed_in?
        %li.nav-item.active
          = link_to "Goodした動画一覧", likes_users_path, class: 'nav-link text-white border text-align: right'
        %li.nav-item.active
          = link_to 'アカウント編集', edit_user_registration_path, class: 'nav-link text-white border text-align: right'
        %li.nav-item.active
          = link_to "#{current_user.name}さんページ", "/users/#{current_user.id}", class: 'nav-link text-white border'
        %li.nav-item.active
          = link_to  "投稿する", "/products/new", class: 'nav-link text-white border'
        %li.nav-item.active
          = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link text-white border'
      - else
        %li.nav-item.active
          = link_to "新規登録", new_user_registration_path, class: 'nav-link text-white border'
        %li.nav-item.active
          = link_to "ログイン", new_user_session_path, class: 'nav-link text-white border'
        %li.nav-item.active
          = link_to 'ゲストログイン（閲覧用）',users_guest_sign_in_path, method: :post, class: 'nav-link yellor-border text-warning'
.header3
  = render 'shared/flash_messages'

  -#   #{current_user.name}さんの
  -# .header__bar.row
  -#   %h1.grid-6
  -#     %a{:href => "/"} Penspinning Videos
  -#   - if user_signed_in?
  -#     .user_nav.grid-6
  -#       %span
  -#         = current_user.name
  -#         %ul.user__info
  -#           %li
  -#             = link_to "マイページ", "/users/#{current_user.id}"
  -#             = link_to "ログアウト", destroy_user_session_path, method: :delete
  -#       = link_to  "投稿する", "/products/new", class: "post"
  -#   - else
  -#     .grid-6
  -#       = link_to "ログイン", new_user_session_path, class: 'post'
  -#       = link_to "新規登録", new_user_registration_path, class: 'post'

app/views/products/_post.html.haml
%header.header1
  %nav.navbar.navbar-expand.navbar-light.up
    = link_to "Penspinning Videos", root_path, class: 'navbar-brand text-white font-weight-bold'
  %nav.navbar.navbar-expand.navbar-light.up
    = form_with(url: search_products_path, local: true, method: :get, class: "search-form") do |form|
      = form.text_field :keyword, placeholder: "検索して下さい", class: "search-input"
      = form.submit "検索", class: "search-btn"
.header2
  %nav.navbar.navbar-expand.navbar-light.down
    %ul.navbar-nav.left__title
      - if user_signed_in?
        %li.nav-item.active
          = link_to "Goodした動画一覧", likes_users_path, class: 'nav-link text-white border text-align: right'
        %li.nav-item.active
          = link_to 'アカウント編集', edit_user_registration_path, class: 'nav-link text-white border text-align: right '
        %li.nav-item.active
          = link_to "#{current_user.name}さんページ", "/users/#{current_user.id}", class: 'nav-link text-white border'
        %li.nav-item.active
          = link_to  "投稿する", "/products/new", class: 'nav-link text-white border'
        %li.nav-item.active
          = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link text-white border'
      - else
        %li.nav-item.active
          = link_to "新規登録", new_user_registration_path, class: 'nav-link text-white border'
        %li.nav-item.active
          = link_to "ログイン", new_user_session_path, class: 'nav-link text-white border'
        %li.nav-item.active
          = link_to 'ゲストログイン（閲覧用）',users_guest_sign_in_path, method: :post, class: 'nav-link yellor-border text-warning'
.header3
  = render 'shared/flash_messages'
.blank

%main.main
  - @products.each do |product|
    .show_search
      .content_show_search
        .content_show_top
          .show_search_left_top
            .show_search_icon
              .show_search_icon_left
                .show_search_icon_left_image
                  - if product.user.image?
                    = image_tag(product.user.image.to_s, class: "user_icon_image",alt:"no-image")
                  - else
                    = image_tag asset_path("default.png"), alt: "no-image"

              .show_search_name
                .show_search_name__top
                  = product.title
                .show_search_time__bottom
                  .show_search__time__bottom--date
                  = product.created_at.strftime('%Y/%m/%d %H:%M:%S')
        .show_search_video_center
          .content_show_video
            = video_tag(product.image_url.to_s, autoplay: false, muted: true, controls: true, preload: true, class: "search_show_video", id: "search_show_video_preview") if product.image?
        .products-search_option
          .favorite_search
            .search_heart
              %i.fas.fa-heart.search_icon_heart
              Good！
              = product.likes.count
          .show_search_page
            = link_to '詳細ページ', "/products/#{product.id}", method: :get, class: "show_search_bottun"
          .optional_search
            .optional_search_btn
              = link_to "#", class: "optional_search_btn_link" do
                = icon('fas', 'flag', class: 'image-icon')
                不適切な動画の通報

app/views/products/create.html.haml
.navigation
  .products-main
    .products-main_title
      %h2
        投稿が完了しました
        .products-done__main__explanation
          = link_to '詳細ページに移動', "/products/#{@product.id}", method: :get, class: "all_return_bottun"
        .products-done__main__explanation
          = link_to "マイページに移動", "/users/#{current_user.id}", class: "all_return_bottun"
        .products-done__main__explanation
          = link_to "トップページに移動", root_path, class: "all_return_bottun"

app/views/products/destory.html.haml
.navigation
  .products-main
    %h2
      消去が完了しました
      .products-done__main__explanation
        = link_to "マイページに移動", "/users/#{current_user.id}", class: "all_return_bottun"
      .products-done__main__explanation
        = link_to "トップページに移動", root_path, class: "all_return_bottun"

app/views/products/edit.html.haml
.blank
.master_form
  .form
    %h2.form_title
      編集画面
    - if flash[:alert]
      %p.alert
        = flash[:alert]
    = form_with(model: @product, local: true) do |form|
      .main_post
        = render partial: "form", locals: { form: form }
        .form-group
          = form.label :pen_tyep_id do
            ペン回し歴
            %span.form-require 必須
          %div
            .select-wrap
              = form.collection_select :pen_history_id, PenHistory.all, :id, :value, {prompt: "選択して下さい", selected: @product.id},class: "select-default"
        .form-group.category
          %label
          ペンの種類
          %span.form-require 必須
          .select-wrap
            - @parents.each do |parent|
              - if @product.category_id == parent.id
                .select-wrap__box.parent
                  = form.collection_select(:category_id, Category.where(ancestry: nil), :id, :name, {prompt: "選択して下さい", selected: parent.parent.id}, {id: "parent"})
                .child-edit
                  = form.collection_select(:category_id, Category.where(params[:category_id]), :id, :name, {prompt: "選択して下さい", selected: parent.id}, {id: "child"})
        .form_submit
          = form.submit "投稿",class: "form_submit_bottun"
        .return
          = link_to "戻る", root_path, class: "return_bottun"
.blank

app/views/products/index.html.haml
= render partial: "post", locals: { product: @products }

= paginate(@products)
.blank
= render "footer"

app/views/products/new.html.haml
.blank
.master_form
  .form
    %h2.form_title
      動画の投稿
    = render 'error_message', locals: {product: @product}
    = form_with(model: @product, local: true) do |form|
      .main_post
        = render partial: "form", locals: { form: form }
        .form-group
          = form.label :pen_history_id do
            ペン回し歴
            %span.form-require 必須
          %div
            .select-wrap
              = form.collection_select :pen_history_id, PenHistory.all, :id, :value, {include_blank: "選択して下さい", selected: "選択して下さい"}, class: "select-default"
        .form-group.category
          %label
          ペンの種類
          %span.form-require 必須
          .select-wrap
            .select-wrap__box.parent
              %select#parent.select-wrap__box--select
                %option{value: 0} 選択して下さい
                - @parents.each do |parent|
                  %option{value: "#{parent.id}"} #{parent.name}
            .child
              = form.collection_select(:category_id, [], :id, :name, {prompt: "選択して下さい"},{class: 'select-wrap__box--select',id: "child"})

        .form_submit
          = form.submit "投稿",class: "form_submit_bottun"
        .return
          = link_to "戻る", root_path, class: "return_bottun"
.blank

app/views/products/search.html.haml
= render partial: "post", locals: { product: @products }

= paginate(@products)
.blank
= render "footer"

app/views/products/show.html.haml
= render "header"
.blank
%main.main
  .show_main
    .content_show_main
      .content_show_top
        .show_main_left_top
          .show_main_icon
            .show_main_icon_left
              .show_main_icon_left_image
                - if @product.user.image?
                  = image_tag(@product.user.image.to_s, class: "user_icon_image",alt:"no-image")
                - else
                  = image_tag asset_path("default.png"), alt: "no-image"
            .show_main_name
              .show_main_name__top
                = @product.title
              .show_main_time__bottom
                .show_main__time__bottom--date
                = @product.created_at.strftime('%Y/%m/%d %H:%M:%S')
        .show_main_rigth_top
          .content_show_posts
            %table
              %tbody
                %tr
                  %th.tag_content
                    ペン回し歴
                  %td.neme_content
                    = @product.pen_history.value
          .content_show_posts
            %table
              %tbody
                %tr
                  %th.tag_content
                    ペンの種類
                  %td.neme_content
                    - @parents.each do |parent|
                      - if @product.category_id == parent.id
                        -# = link_to "#" do
                        -#   = parent.parent.name
                        = link_to "#" ,class: "category_font" do
                          = parent.name

      .show_main_video_center
        .content_show_video
          = video_tag(@product.image_url.to_s, autoplay: false, muted: true, controls: true, preload: true, class: "main_show_video", id: "main_show_video_preview") if @product.image?
      .products-box__option
        .favorite
          = render 'likes/like', product: @product
        .slow_video
          %button#prev-frame コマ戻り
          %button#next-frame コマ送り
        .optional
          .optional__btn
            = link_to "#", class: "optional__btn__link" do
              = icon('fas', 'flag', class: 'image-icon')
              不適切な動画の通報
      .content_main_down
        %table
          %tbody
            %tr
              %th.main_show_contes_th
                動画の説明
              %td.main_show_contes_tb
                = simple_format(@product.text)
      .comments-box
        .message-box
          -if @comments
            -@comments.each do |comment|
              .comments-box__message
                .comments-box__message__products
                  .comments-box__message__products__user
                    .comments-box__message__products__user__name
                      = comment.product.title
                  .comments-box__message__products__body
                    = comment.text
                    .comments-box__message__products__body__icons
                      .comments-box__message__products__body__icons__left
                        = icon('fas', 'history')
                        %span
                          = comment.created_at.strftime("%Y年%m月%d日 %H時%M分")
                    - if user_signed_in? && current_user.id == @product.user_id
                      .comments-box__message__products__body__icons__right
                        .message-delete
                          = link_to "/products/#{@product.id}/comments/#{comment.id}", method:"delete", id: :delete_btn do
                            = icon('fas', 'trash')

        -if current_user
          .caution-area
            相手のことを考えて丁寧なコメントを心がけましょう。
            %br/
            不快な言葉遣いなどは利用制限や退会処分となることがあります。
          = form_for [@product, @comment], html: { id: :new_comment } do |f|
            = f.text_area :text, placeholder: "コメントの文字数は250文字まで。",class: "comment-area"
            .comment-btn
              = f.submit "コメントする", class: "comment-btn__submit"
.blank
.main_show_retrun
  = link_to 'トップページ', "/", method: :get, class: "show_main_return_bottun"
= render "products/footer"

app/views/products/update.html.haml
.navigation
  .products-main
    .products-main_title
      %h2
        更新が完了しました
        .products-done__main__explanation
          = link_to '詳細ページに移動', "/products/#{@product.id}", method: :get, class: "all_return_bottun"
        .products-done__main__explanation
          = link_to "マイページに移動", "/users/#{current_user.id}", class: "all_return_bottun"
        .products-done__main__explanation
          = link_to "トップページに移動", root_path, class: "all_return_bottun"